### ISSUE TITLE
Compiling Microemacs on Windows using 64-bit gcc

### ISSUE THREAD

**Issue by eddavis2** [freakout42/microemacs#1]
I could not get Microemacs to compile on Windows 10, using 64-bit gcc.  
gcc --version reports: gcc.exe (tdm64-1) 9.2.0

After making a few small changes to ed.h, it was able to compile.  I'd issue a pull request, but I have not figured out how to do that :(   Anyway, here are my changes:

***** old-ed.h
   24:
   25:  #if (_WIN32)
   26:  #define V7      0
***** ed.h
   24:
   25:  #if (_WIN32 | _WIN64)
   26:  #define V7      0
*****

***** old-ed.h
  434:
  435:  #ifdef SYS_V
  436:  #include <stdlib.h>
***** ed.h
  434:
  435:  #if SYS_V | W32
  436:  #include <stdlib.h>
*****

***** old-ed.h
  438:
  439:  #if (!defined(_STDLIB_H) && !defined(_STDLIB_INCLUDED) && !defined(_STDLIB_H_))
  440:  extern  char *malloc();
***** ed.h
  438:
  439:  #if (!defined(_STDLIB_H) && !defined(_STDLIB_INCLUDED) && !defined(_STDLIB_H_) && !defined(_INC_STDLIB))
  440:  extern  char *malloc();
*****

**Comment by freakout42** [comment]
thanks - see this commit - would be nice if you could check again
https://github.com/freakout42/microemacs/commit/7278f938efda2ffa07009add5c783ce1fae6854e

**Comment by eddavis2** [comment]
Yep, works fine.
Thanks!


On Friday, October 14, 2022 at 10:26:19 AM EDT, Axel K. Reinhold ***@***.***> wrote: 

thanks - see this commit - would be nice if you could check again
7278f93
